# Dependencies
markdown:	kramdown
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thinny
tagline:	'blog'
description:	'My personal blog.'
url:		http://camporez.com

author:
  name:		'Ian Camporez Brunelli'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/TheMatthewWest
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/mwestt
    desc:	Fork me on github

  # - icon:	googleplus-alt
  #   url:	https://google.com/+IanCamporezBrunelli
  #   desc:	Add me on google+

  # - icon:	feed
  #   url:	http://camporez.com/atom.xml
  #   desc:	Subscribe to my feed

  - icon:	linkedin
    url:	https://www.linkedin.com/in/mwestt/
    desc:	Connect with me on linkedin
  

menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Based on Thinny by Ian Brunelli
  url: https://github.com/brunelli 
  type_title:	MIT License
  type_url: https://github.com/camporez/Thinny/blob/master/LICENSE
